### ISSUE TITLE
OTA fixes

### ISSUE THREAD

**Issue by snevas** [WeAreFairphone/android_device_fairphone_FP2#2]
- https://github.com/chrmhoffmann/android_device_fairphone_FP2/pull/1
Workaround:
adb shell:
su -
cd /
mount -o rw,remount,rw /
cp fstab.qcom fstab.back
sed '0,/misc/{s/misc/pad/}' fstab.qcom > fstab.new
mv fstab.new fstab.qcom
mount -o ro,remount,ro /

- Package z3ntu's recovery into the zip?: https://private.z3ntu.xyz/fairphone/TWRP_3.1.1-0-ota-fix/TWRP_3.1.1-0-ota-fix.img

-  Replace the string conf_update_server_url_def value  inside values.xml of the OTA source code to https://fp2.joutubes.nl/api
Workaround:
adb shell:
su -
cd /system
mount -o rw,remount,rw /system
echo "cm.updater.uri=https://fp2.joutubes.nl/api" >> build.prop
mount -o ro,remount,ro /system
(https://blog.julianxhokaxhiu.com/how-the-cm-ota-server-works-and-how-to-implement-and-use-ours/)

**Comment by z3ntu** [comment]
You don't have to backup the /fstab.qcom file. Just reboot and it's reverted to it's original state.
Also hopefully the recovery change will soon be merged into the official builds. :)

**Comment by snevas** [comment]
True, but we need 1 step to get it overwritten. `sed '0,/misc/{s/misc/pad/}' fstab.qcom >fstab.qcom` results in a empty file :)

**Comment by z3ntu** [comment]
also why not "yes -i"?

**Comment by z3ntu** [comment]
Am on mobile and autocorrect is shitty

-> sed -i

**Comment by z3ntu** [comment]
That worked for me:
```
su
mount -o rw,remount /
sed -i '0,/misc/{s/misc/pad/}' fstab.qcom
# (optionally remount it back to ro)
setprop cm.updater.uri https://fp2.joutubes.nl/api
```

**Comment by snevas** [comment]
Made a pull request that hopefully does the trick

**Comment by snevas** [comment]
Confirmed working!
